//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoUniversity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meet_participant
    {
        public int id_Meet_participant { get; set; }
        public int Id_participant { get; set; }
        public int Id_meet { get; set; }
    
        public virtual Meet Meet { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
