
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KLich
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

 public partial class Participant
 {

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Participant()
    {

        this.Meet_participant = new HashSet<Meet_participant>();

    }


    public int Id_participant { get; set; }


    [Required]
    [StringLength(100)]
    public string FirstName { get; set; }

    
    [StringLength(100)]
    public string SureName { get; set; }

    [Required]
    [StringLength(50)]
    [EmailAddress]
    public string Email { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Meet_participant> Meet_participant { get; set; }

}

}
